# Generated by Django 2.0.5 on 2018-06-04 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catdb', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='username',
        ),
    ]
