# Generated by Django 2.0.5 on 2018-06-04 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catdb', '0002_auto_20180604_1617'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='username',
            new_name='UserInfo',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='password',
            new_name='pwd',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='username',
            new_name='user',
        ),
    ]
